services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_wordpress

  wordpress:
    image: wordpress:latest
    container_name: wp_app
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    networks:
      - red_wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_pass
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - red_wordpress

volumes:
  db_data:
  wp_data:

networks:
  red_wordpress:
